package com.neohope.nlp.refn;

import java.util.HashMap;
import java.util.Map;

public class HanlpDict {
	public static Map<String,String> relationDict=new HashMap<>();
	public static Map<String,String> natureDict=new HashMap<>();
	
	static {
		relationDict.put("ATT", "定中关系");
		relationDict.put("QUN", "数量关系");
		relationDict.put("COO", "并列关系");
		relationDict.put("APP", "同位关系");
		relationDict.put("LAD", "前附加关系");
		relationDict.put("RAD", "后附加关系");
		relationDict.put("RIM", "比拟关系");
		relationDict.put("VOB", "动宾关系");
		relationDict.put("SBV", "主谓关系");
		relationDict.put("POB", "介宾关系");
		relationDict.put("MT", "语态结构");
		relationDict.put("IS", "独立结构");
		relationDict.put("CMP", "动补结构");
		relationDict.put("ADV", "状中结构");
		relationDict.put("VV", "联动结构");
		relationDict.put("CNJ", "关联结构");
		relationDict.put("IC", "独立分句");
		relationDict.put("DC", "依存分句");
		relationDict.put("DE", "的");
		relationDict.put("DI", "地");
		relationDict.put("DEI", "得");
		relationDict.put("BA", "把");
		relationDict.put("BEI", "被");
		relationDict.put("WP", "标点符号");
		
		natureDict.put("Mg", "甲乙丙丁之类的数词");
		natureDict.put("Rg", "古汉语代词性语素");
		natureDict.put("a", "形容词");
		natureDict.put("ad", "副形词");
		natureDict.put("ag", "形容词性语素");
		natureDict.put("al", "形容词性惯用语");
		natureDict.put("an", "名形词");
		natureDict.put("b", "区别词");
		natureDict.put("begin", "仅用于始##始，不会出现在分词结果中");
		natureDict.put("bg", "区别语素");
		natureDict.put("bl", "区别词性惯用语");
		natureDict.put("c", "连词");
		natureDict.put("cc", "并列连词");
		natureDict.put("d", "副词");
		natureDict.put("dg", "辄,俱,复之类的副词");
		natureDict.put("dl", "连语");
		natureDict.put("e", "叹词");
		natureDict.put("end", "仅用于终##终，不会出现在分词结果中");
		natureDict.put("f", "方位词");
		natureDict.put("g", "学术词汇");
		natureDict.put("gb", "生物相关词汇");
		natureDict.put("gbc", "生物类别");
		natureDict.put("gc", "化学相关词汇");
		natureDict.put("gg", "地理地质相关词汇");
		natureDict.put("gi", "计算机相关词汇");
		natureDict.put("gm", "数学相关词汇");
		natureDict.put("gp", "物理相关词汇");
		natureDict.put("h", "前缀");
		natureDict.put("i", "成语");
		natureDict.put("j", "简称略语");
		natureDict.put("k", "后缀");
		natureDict.put("l", "习用语");
		natureDict.put("m", "数词");
		natureDict.put("mg", "数语素");
		natureDict.put("mq", "数量词");
		natureDict.put("n", "名词");
		natureDict.put("nb", "生物名");
		natureDict.put("nba", "动物名");
		natureDict.put("nbc", "动物纲目");
		natureDict.put("nbp", "植物名");
		natureDict.put("nf", "食品，比如“薯片”");
		natureDict.put("ng", "名词性语素");
		natureDict.put("nh", "医药疾病等健康相关名词");
		natureDict.put("nhd", "疾病");
		natureDict.put("nhm", "药品");
		natureDict.put("ni", "机构相关（不是独立机构名）");
		natureDict.put("nic", "下属机构");
		natureDict.put("nis", "机构后缀");
		natureDict.put("nit", "教育相关机构");
		natureDict.put("nl", "名词性惯用语");
		natureDict.put("nm", "物品名");
		natureDict.put("nmc", "化学品名");
		natureDict.put("nn", "工作相关名词");
		natureDict.put("nnd", "职业");
		natureDict.put("nnt", "职务职称");
		natureDict.put("nr", "人名");
		natureDict.put("nr1", "复姓");
		natureDict.put("nr2", "蒙古姓名");
		natureDict.put("nrf", "音译人名");
		natureDict.put("nrj", "日语人名");
		natureDict.put("ns", "地名");
		natureDict.put("nsf", "音译地名");
		natureDict.put("nt", "机构团体名");
		natureDict.put("ntc", "公司名");
		natureDict.put("ntcb", "银行");
		natureDict.put("ntcf", "工厂");
		natureDict.put("ntch", "酒店宾馆");
		natureDict.put("nth", "医院");
		natureDict.put("nto", "政府机构");
		natureDict.put("nts", "中小学");
		natureDict.put("ntu", "大学");
		natureDict.put("nx", "字母专名");
		natureDict.put("nz", "其他专名");
		natureDict.put("o", "拟声词");
		natureDict.put("p", "介词");
		natureDict.put("pba", "介词“把”");
		natureDict.put("pbei", "介词“被”");
		natureDict.put("q", "量词");
		natureDict.put("qg", "量词语素");
		natureDict.put("qt", "时量词");
		natureDict.put("qv", "动量词");
		natureDict.put("r", "代词");
		natureDict.put("rg", "代词性语素");
		natureDict.put("rr", "人称代词");
		natureDict.put("ry", "疑问代词");
		natureDict.put("rys", "处所疑问代词");
		natureDict.put("ryt", "时间疑问代词");
		natureDict.put("ryv", "谓词性疑问代词");
		natureDict.put("rz", "指示代词");
		natureDict.put("rzs", "处所指示代词");
		natureDict.put("rzt", "时间指示代词");
		natureDict.put("rzv", "谓词性指示代词");
		natureDict.put("s", "处所词");
		natureDict.put("t", "时间词");
		natureDict.put("tg", "时间词性语素");
		natureDict.put("u", "助词");
		natureDict.put("ud", "助词");
		natureDict.put("ude1", "的 底");
		natureDict.put("ude2", "地");
		natureDict.put("ude3", "得");
		natureDict.put("udeng", "等 等等 云云");
		natureDict.put("udh", "的话");
		natureDict.put("ug", "过");
		natureDict.put("uguo", "过");
		natureDict.put("uj", "助词");
		natureDict.put("ul", "连词");
		natureDict.put("ule", "了 喽");
		natureDict.put("ulian", "连 （“连小学生都会”）");
		natureDict.put("uls", "来讲 来说 而言 说来");
		natureDict.put("usuo", "所");
		natureDict.put("uv", "连词");
		natureDict.put("uyy", "一样 一般 似的 般");
		natureDict.put("uz", "着");
		natureDict.put("uzhe", "着");
		natureDict.put("uzhi", "之");
		natureDict.put("v", "动词");
		natureDict.put("vd", "副动词");
		natureDict.put("vf", "趋向动词");
		natureDict.put("vg", "动词性语素");
		natureDict.put("vi", "不及物动词（内动词）");
		natureDict.put("vl", "动词性惯用语");
		natureDict.put("vn", "名动词");
		natureDict.put("vshi", "动词“是”");
		natureDict.put("vx", "形式动词");
		natureDict.put("vyou", "动词“有”");
		natureDict.put("w", "标点符号");
		natureDict.put("wb", "百分号千分号，全角：％ ‰   半角：%");
		natureDict.put("wd", "逗号，全角：， 半角：,");
		natureDict.put("wf", "分号，全角：； 半角： ;");
		natureDict.put("wh", "单位符号，全角：￥ ＄ ￡  °  ℃  半角：$");
		natureDict.put("wj", "句号，全角：。");
		natureDict.put("wky", "右括号，全角：） 〕  ］ ｝ 》  】 〗 〉 半角： ) ] { >");
		natureDict.put("wkz", "左括号，全角：（ 〔  ［  ｛  《 【  〖 〈   半角：( [ { <");
		natureDict.put("wm", "冒号，全角：： 半角： :");
		natureDict.put("wn", "顿号，全角：、");
		natureDict.put("wp", "破折号，全角：——   －－   ——－   半角：---  ----");
		natureDict.put("ws", "省略号，全角：……  …");
		natureDict.put("wt", "叹号，全角：！ 半角：!");
		natureDict.put("ww", "问号，全角：？ 半角：?");
		natureDict.put("wyy", "右引号，全角：” ’ 』");
		natureDict.put("wyz", "左引号，全角：“ ‘ 『");
		natureDict.put("x", "字符串");
		natureDict.put("xu", "网址URL");
		natureDict.put("xx", "非语素字");
		natureDict.put("y", "语气词(delete yg)");
		natureDict.put("yg", "语气语素");
		natureDict.put("z", "状态词");
		natureDict.put("zg", "状态词");
	}
}
